### ISSUE TITLE
Chord Description Test Length

### ISSUE THREAD

**Issue by rbeerster** [einaregilsson/ChordImageGenerator#10]
If you specify a C#sus2/E chord description (ala Andy Summers), there is not enough room to display the entire description:

![image](https://user-images.githubusercontent.com/29076032/91671255-2b24b580-eaf3-11ea-8e76-f97f7da40848.png)

**Comment by rbeerster** [comment]
Sorry Chord Description Text Length.

**Comment by psifidotos** [comment]
Try,  C#_sus2_/E

**Comment by rbeerster** [comment]
Thanks for the idea.  I ended up using:  C_#sus2_/E.
