### ISSUE TITLE
Continuation of the project

### ISSUE THREAD

**Issue by rluetzner** [einaregilsson/ChordImageGenerator#11]
A few weeks ago I got a surprising email. It came from an avid user of http://chordgenerator.net and they were devastated that the service was no longer available. They looked up the project on GitHub and started contacting contributors, amongst them me.

They had done some research on Einar Egilsson and that's how I learned that sadly he's passed away.

I'd be interested in keeping this project alive. In fact, I've already put in some work to make this tool platform independent and put up a new hosted instance at https://chordgenerator.luetzners.de.

I forked this project as https://github.com/rluetzner/ChordImageGenerator.

**Comment by gzur** [comment]
Hi @rluetzner 

Thanks for reaching out. I've added [a notice to the README](https://github.com/einaregilsson/ChordImageGenerator/commit/9511ec657b652392de036f9a72f5bb1f63e8924f) and I'm going to archive this repository.
